### ISSUE TITLE
Scrollable div table header goes out of box

### ISSUE THREAD

**Issue by warlockdn** [oma/table-fixed-header#19]
I took your example and added a div around the table and made it work with width: 500px; and overflow: auto;

So, now when I scroll down the table head row goes out of box.

Can you help me fix it ?

Here is a working example.

http://jsfiddle.net/warlockdn/19sdye9a/

Thanks.

**Comment by oma** [comment]
sorry, I don't have capacity to follow up on this repo. If you solve it, please share the solution for others, it's good karma :)

**Comment by warlockdn** [comment]
So I posted the error in stackoverflow and Frank helped me to make it worked though I did not use your plugin. Please follow the link.

http://stackoverflow.com/questions/33342854/table-with-multiple-inner-tables-and-fixed-header-table-with-horizontal-scroll/33362189
